[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# Environment variables will be set in Netlify dashboard
# Required variables:
# - VITE_EMAILJS_PUBLIC_KEY
# - VITE_EMAILJS_SERVICE_ID
# - VITE_EMAILJS_TEMPLATE_ID

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self' https://challenges.cloudflare.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://challenges.cloudflare.com https://cdn.emailjs.com; style-src 'self' 'unsafe-inline';" 