name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify build
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed - dist directory not found"
            exit 1
          fi

      - name: Prepare deployment
        run: |
          # Create a new directory structure
          mkdir -p public_html
          # Move all contents from dist to public_html
          cp -r dist/* public_html/
          # Create a simple .htaccess file for proper routing
          echo 'RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteCond %{REQUEST_FILENAME} !-l
          RewriteRule . /index.html [L]' > public_html/.htaccess

      - name: Trigger Hostinger Deployment
        if: success()
        run: |
          echo "Triggering Hostinger deployment..."
          curl -X POST https://webhooks.hostinger.com/deploy/c8cec9d8493593e95aa221fbd9c7716a \
            -H "Content-Type: application/json" \
            -d '{
              "ref": "main",
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "build": true,
              "deploy_path": "public_html"
            }'