name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    permissions:
      contents: write
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          clean: true
          fetch-depth: 0

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install all dependencies
        run: npm ci

      - name: Clean previous build
        run: rm -rf dist

      - name: Build
        run: npm run build

      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add dist -f
          git commit -m "chore: Update build files [skip ci]" || echo "No changes to commit"
          git push