name: Build and Deploy to Hostinger

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    permissions:
      contents: write
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          clean: true
          fetch-depth: 0

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install all dependencies
        run: npm ci

      - name: Clean previous build
        run: rm -rf dist

      - name: Build
        run: npm run build

      - name: Prepare for Hostinger
        run: |
          # Create a temporary directory for deployment
          mkdir -p temp_deploy
          # Copy build files to deployment directory
          cp -r dist/* temp_deploy/
          # Create .htaccess file for SPA routing
          echo "RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteCond %{REQUEST_FILENAME} !-l
          RewriteRule . /index.html [L]" > temp_deploy/.htaccess
          # Remove existing dist directory
          rm -rf dist
          # Move deployment files to dist
          mv temp_deploy dist

      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add dist -f
          git commit -m "chore: Update build files [skip ci]" || echo "No changes to commit"
          git push

      - name: Trigger Hostinger Deployment
        if: success()
        run: |
          curl -X POST https://webhooks.hostinger.com/deploy/c8cec9d8493593e95aa221fbd9c7716a \
          -H "Content-Type: application/json" \
          -d '{"ref": "main", "repository": "${{ github.repository }}", "commit": "${{ github.sha }}"}'