name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Hostinger
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "109.106.250.162"
          username: "u534640516"
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: "65002"
          source: "dist/*"
          target: "/public_html"
          strip_components: 1 